services:
  network-deploy-service:
    deploy:
      resources:
        limits:
          memory: 700m
    env_file: ./.env
    environment:
      TZ: "Europe/Kyiv"
    networks:
      - expense-network

  microservice-base-config:
    extends:
      service: network-deploy-service
    environment:
      LOGGING_CONFIG: "classpath:logback-docker.xml"
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 50000
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

  microservice-config-server-config:
    extends:
      service: microservice-base-config
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      #SPRING_CONFIG_IMPORT: configserver:http://config-server:8888/
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 8888

  microservice-eureka-config:
    extends:
      service: microservice-config-server-config
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka/
