global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'config-server:8888' ]

  - job_name: 'eureka-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eureka-service:8761' ]

  - job_name: 'gateway-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gateway-server:8072' ]

  - job_name: 'authentication-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'authentication-service:8400' ]

  - job_name: 'expense-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'expense-service:8100' ]

  - job_name: 'recognizer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'recognizer-service:8300' ]

  - job_name: 'telegram-bot-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'telegram-bot-service:8200' ]
