server:
  port: 8100

spring:
  application:
    name: expense-service
  profiles:
    active: ${SPRING_APPLICATION_PROFILE:dev}
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8888}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  #config: classpath:logback-local.xml
  level:
    com:
      redartis:
        expense: INFO
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "expense-service"
    description: "Expense Service Application"
    version: "1.0.0"
