server:
  port: 8100

spring:
  application:
    name: expense-service
  profiles:
    active: ${SPRING_APPLICATION_PROFILE:dev}
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8888}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

filters:
  authorization-header:
    header-value: ${INTERNAL_KEY_HEADER:X-INTERNAL-KEY}

default-category:
  categories:
    -
      name: Salary
      type: INCOME
    -
      name: Groceries
      type: EXPENSE
    -
      name: Transport
      type: EXPENSE
    -
      name: Apartments rent
      type: EXPENSE

recent-activity:
  activityDays: 30

admin:
  allowed_users:
    RedArt, admin

long-polling:
  tracker:
    period-of-inactivity: 10_000
