server:
  port: 8200

spring:
  application:
    name: telegram-bot-service
  profiles:
    active: ${SPRING_APPLICATION_PROFILE:dev}
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8888}

