server:
  port: 8200

spring:
  application:
    name: telegram-bot-service
  profiles:
    active: ${SPRING_APPLICATION_PROFILE:dev}
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8888}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  # Zipkin config
  tracing:
    sampling:
      probability: 1.0

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "telegram-bot-service"
    description: "Telegram Bot Service Application"
    version: "1.0.0"

logging:
  config: classpath:logback-local.xml
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
